//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public int scheduleId { get; set; }
        public int scheduleDay { get; set; }
        public int scheduleNumLesson { get; set; }
        public int scheduleCourseId { get; set; }
        public int scheduleGroupId { get; set; }
        public Nullable<int> scheduleClassRoomId { get; set; }
    
        public virtual Cours Cours { get; set; }
        public virtual Group Group { get; set; }
        public virtual Room Room { get; set; }
    }
}
